# Generated by Django 2.2.3 on 2019-07-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('study', models.TextField()),
                ('labwork', models.TextField()),
                ('cmd', models.CharField(max_length=200)),
                ('cmdexp', models.TextField(max_length=200)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
